### ISSUE TITLE
Open Client 

### ISSUE THREAD

**Issue by rui00rodrigues** [bfabiszewski/phpTrackme#3]
Do you have any updates on this project?
I have find a good solution for open client: https://github.com/nickfox/GpsTracker

Any geofencing solution?

**Comment by bfabiszewski** [comment]
Sorry for late response. 
As TrackMe app in its recent versions became useless for my needs, I temporarily stopped playing with my viewer. 
I am still looking for an open client as a replacement. I looked at your link. Looks promising for the start. When I get more time I could use it as a base or start a new client from the scratch.

**Comment by dschense** [comment]
https://github.com/tananaev/traccar

**Comment by bfabiszewski** [comment]
Thanks for the link. I'll have a look. 
At the first glance it seems overcomplicated for my purposes. What I am looking for is a lightweight app that uploads GPS basic data over GET or POST. With ability to store data offline if server is unreachable and autouploading when the connection is restored.

**Comment by bfabiszewski** [comment]
I decided to go my own way writing android client from scratch:
https://github.com/bfabiszewski/ulogger-android
